import type { BlogPost } from "@/lib/blog";

const author = "My Editing and Proofreading Desk";
const published = "2026-08-04";

export const requestedBlogPosts: BlogPost[] = [
  {
    title: "Human vs AI Proofreading: What Each Catches and Misses",
    slug: "ai-proofreading-vs-human-proofreading",
    excerpt: "Compare AI proofreading and human proofreading for grammar, meaning, tone, consistency, confidentiality, and final document risk.",
    category: "AI and Writing Tools",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "8 min read",
    metaTitle: "AI Proofreading vs Human Proofreading | What Each Misses",
    metaDescription: "Compare AI proofreading vs human proofreading for grammar, meaning, tone, consistency, confidentiality, and final document review.",
    heroImage: "/images/blog/editing-vs-proofreading-hero-v2.png",
    heroImageAlt: "Human editor comparing proofreading marks with automated editing suggestions on a document",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "what-ai-catches", label: "What AI catches" },
      { id: "what-humans-catch", label: "What humans catch" },
      { id: "comparison", label: "Comparison table" },
      { id: "safe-workflow", label: "Safe workflow" },
      { id: "choose-human", label: "When to choose human review" },
    ],
    body: [
      {
        id: "quick-answer",
        heading: "AI proofreading vs human proofreading: the short answer",
        paragraphs: [
          ["AI proofreading can be useful for a quick first pass on spelling, grammar, repeated words, and obvious sentence problems. Human proofreading is stronger when meaning, tone, context, confidentiality, formatting, document-wide consistency, and final judgment matter."],
          ["The safest workflow is not AI or human in isolation. Use AI cautiously for low-risk early checks, then use ", { text: "professional proofreading services", href: "/proofreading-services" }, " for important academic, business, manuscript, application, or submission-ready documents."],
        ],
      },
      {
        id: "what-ai-catches",
        heading: "What AI proofreading tools can catch",
        paragraphs: [
          ["AI tools can identify many visible language issues quickly. They may flag spelling variants, repeated words, missing punctuation, grammar patterns, wordiness, and sentences that could be easier to read."],
          ["They are useful when you need a first pass before sharing a draft. Our ", { text: "free AI editing tool", href: "/ai-editing-tool" }, " is designed for that early review stage, not as a replacement for a human final check."],
        ],
        bullets: [
          ["Obvious spelling and punctuation issues"],
          ["Repeated words or simple grammar patterns"],
          ["Overlong sentences that may need attention"],
          ["Possible tone or clarity issues in short text"],
        ],
      },
      {
        id: "what-humans-catch",
        heading: "What human proofreaders catch that AI can miss",
        paragraphs: [
          ["A human proofreader reads the document as communication. They can ask whether a correction preserves the writer's meaning, whether a term is discipline-specific, whether a business claim has been changed accidentally, and whether a sentence is technically correct but unsuitable for the reader."],
          ["Human review is especially important for documents with confidential information, citation rules, tables, figures, formatting requirements, or high-stakes consequences. Our ", { text: "editorial policy", href: "/editorial-policy" }, " explains the boundaries of responsible human editing."],
        ],
        bullets: [
          ["Meaning changes introduced by automated suggestions"],
          ["Inconsistent terms across chapters or sections"],
          ["Tone that does not fit the audience"],
          ["Formatting, captions, references, and final-file issues"],
          ["Questions that require author confirmation rather than automatic rewriting"],
        ],
      },
      {
        id: "comparison",
        heading: "AI proofreading vs human proofreading comparison",
        paragraphs: [["Use this comparison before deciding how much review your document needs."]],
        table: {
          headers: ["Need", "AI proofreading", "Human proofreading"],
          rows: [
            ["Speed", "Fast for short text", "Depends on length, scope, and turnaround"],
            ["Context", "May miss discipline or audience nuance", "Can preserve meaning and reader expectations"],
            ["Confidentiality", "Depends on the tool and its data handling", "Handled through the service's submission workflow"],
            ["Formatting", "Limited for complex files", "Can review supplied document presentation"],
            ["Final accountability", "Suggestions need human approval", "Corrections still require author approval"],
          ],
        },
      },
      {
        id: "safe-workflow",
        heading: "A safe proofreading workflow",
        paragraphs: [
          ["Start by cleaning obvious errors yourself. Use AI only on text you are allowed to submit to that tool, and review every suggestion before accepting it. Then use a human final review when the document must preserve exact meaning, confidential information, citation integrity, or institutional requirements."],
        ],
        numberedSteps: [
          ["Freeze the draft version you want reviewed."],
          ["Run a low-risk first pass for obvious language issues."],
          ["Reject suggestions that change facts, claims, tone, or terminology."],
          ["Use a human proofreader for the final document."],
          ["Review the returned file before submission."],
        ],
      },
      {
        id: "choose-human",
        heading: "When human proofreading is the better choice",
        paragraphs: [
          ["Choose human proofreading when the document is academic, professional, client-facing, application-related, confidential, or close to final submission. AI can assist the early clean-up, but final judgment belongs with a person who can read context and leave questions where the author must decide."],
          ["Ready for a final review? ", { text: "Upload your document securely", href: "/submit" }, " or compare ", { text: "pricing", href: "/pricing" }, " before you begin."],
        ],
      },
    ],
    faq: [
      { question: "Is AI proofreading enough for important documents?", answer: "Usually not. AI can help with a first pass, but important documents benefit from human review for meaning, tone, confidentiality, formatting, and document-wide consistency." },
      { question: "Can AI proofreading change my meaning?", answer: "Yes. Automated suggestions can make a sentence smoother while changing the writer's intended meaning, technical term, claim strength, or citation relationship." },
      { question: "Should I use AI before hiring a proofreader?", answer: "You can use AI cautiously for low-risk early checks, but review every suggestion and avoid uploading confidential or restricted material to tools that are not permitted." },
    ],
    internalLinks: [
      { href: "/ai-editing-tool", label: "Try the AI tool", description: "Use a quick first pass for short text before human review." },
      { href: "/proofreading-services", label: "Professional proofreading", description: "Get a human final check for important documents." },
      { href: "/editorial-policy", label: "Editorial policy", description: "Review the boundaries of responsible editing and proofreading." },
    ],
  },
  {
    title: "Can You Use AI to Proofread a Thesis or Dissertation?",
    slug: "ai-proofreading-thesis-dissertation",
    excerpt: "Learn when AI proofreading may help thesis or dissertation writers, where it can create risk, and why human final review still matters.",
    category: "AI and Writing Tools",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "8 min read",
    metaTitle: "AI Proofreading Thesis Guide | Risks and Human Review",
    metaDescription: "Learn how to use AI proofreading for a thesis carefully, including risks to meaning, confidentiality, citations, policies, and human review.",
    heroImage: "/images/blog/thesis-proofreading-checklist-hero-v2.png",
    heroImageAlt: "Doctoral thesis pages beside proofreading notes and cautious AI review prompts",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "appropriate-use", label: "Appropriate use" },
      { id: "risks", label: "Risks" },
      { id: "policy", label: "Institutional policies" },
      { id: "citations", label: "Sources and citations" },
      { id: "human-review", label: "Human final review" },
    ],
    body: [
      {
        id: "quick-answer",
        heading: "Can you use AI to proofread a thesis?",
        paragraphs: [
          ["You may be able to use AI to proofread a thesis or dissertation for basic language prompts, but only if your institution permits it and the tool's data handling is appropriate for your material. AI should not be used to hide authorship, bypass academic-integrity rules, invent citations, or make research decisions."],
          ["Use AI as an early support tool, then rely on your own judgment, supervisor guidance, and a human final review for the submission version."],
        ],
      },
      {
        id: "appropriate-use",
        heading: "Appropriate support AI can provide",
        paragraphs: [["AI may help you spot repeated words, long sentences, spelling variants, inconsistent capitalization, or places where a sentence seems unclear. It can also help you build a checklist for your own manual proofreading pass."]],
        bullets: [
          ["Finding possible grammar or punctuation issues"],
          ["Flagging sentences that may be too long"],
          ["Prompting you to check terminology consistency"],
          ["Helping create a proofreading schedule"],
        ],
      },
      {
        id: "risks",
        heading: "Risks to meaning, confidentiality, and academic integrity",
        paragraphs: [
          ["Theses and dissertations contain specialist terminology, unpublished research, participant information, ethics material, and intellectual property. Uploading restricted text to a tool without permission can create confidentiality problems."],
          ["AI can also flatten academic tone, strengthen claims beyond the evidence, remove cautious wording, or change a technical term. Review every suggestion before accepting it."],
        ],
      },
      {
        id: "policy",
        heading: "Check institutional policies before using AI",
        paragraphs: [
          ["Universities and departments set their own rules for AI use, acknowledgement, data security, and acceptable writing support. Follow the policy that applies to your degree, module, supervisor, or journal. If the rule is unclear, ask before using the tool."],
          ["Our ", { text: "editorial policy", href: "/editorial-policy" }, " follows the same principle: editing support should preserve the writer's authorship and should not create research, evidence, or assessed content."],
        ],
      },
      {
        id: "citations",
        heading: "AI should not verify sources or citations for you",
        paragraphs: [["Do not ask AI to invent missing references, complete DOIs, or confirm a source it cannot inspect. Citation accuracy belongs to the author. Use your reference manager, source PDFs, library records, journal pages, and institutional style guidance to verify source details."]],
      },
      {
        id: "human-review",
        heading: "Use a human final review for the submission version",
        paragraphs: [
          ["A human reviewer can consider meaning, discipline, formatting, citations, tables, figures, and comments that require author decisions. For a staged workflow, start with ", { text: "how to proofread a dissertation", href: "/blog/how-to-proofread-a-dissertation-before-submission" }, ", then use the ", { text: "dissertation proofreading service", href: "/dissertation-proofreading" }, " if you want an independent final read."],
        ],
      },
    ],
    faq: [
      { question: "Can AI proofread a dissertation safely?", answer: "Only within the rules that apply to your institution and only with material that is safe to upload. Confidential or restricted research should not be pasted into tools that are not approved." },
      { question: "Can AI check thesis citations?", answer: "AI may flag visible inconsistencies, but authors must verify every source, citation, DOI, URL, and reference-list entry against reliable records." },
      { question: "Should I disclose AI proofreading?", answer: "Follow your institution's policy. This article does not advise hiding AI use or bypassing academic-integrity systems." },
    ],
    internalLinks: [
      { href: "/ai-editing-tool", label: "AI editing tool", description: "Use a quick first pass on short, permitted text." },
      { href: "/dissertation-proofreading", label: "Dissertation proofreading", description: "Get human review for language, consistency, formatting, and presentation." },
      { href: "/editorial-policy", label: "Editorial policy", description: "Review the boundaries of ethical editing support." },
    ],
  },
  {
    title: "How Long Does Dissertation Proofreading Take?",
    slug: "how-long-does-dissertation-proofreading-take",
    excerpt: "Understand the factors that affect dissertation proofreading time, including word count, draft quality, references, formatting, review passes, and tracked changes.",
    category: "Thesis and Dissertation",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "7 min read",
    metaTitle: "How Long Does Dissertation Proofreading Take?",
    metaDescription: "Learn how long dissertation proofreading takes and what affects timing: word count, draft quality, tables, references, formatting, and review passes.",
    heroImage: "/images/blog/dissertation-proofreading-checklist-hero.png",
    heroImageAlt: "Dissertation draft, calendar, and proofreading notes showing turnaround planning",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "time-factors", label: "Timing factors" },
      { id: "review-passes", label: "Review passes" },
      { id: "tracked-changes", label: "Tracked changes" },
      { id: "plan", label: "How to plan" },
    ],
    body: [
      {
        id: "quick-answer",
        heading: "How long dissertation proofreading takes",
        paragraphs: [["Dissertation proofreading time depends on word count, language condition, formatting complexity, tables, figures, references, deadline, and the number of review passes needed. There is no universal timeline that fits every dissertation."]],
      },
      {
        id: "time-factors",
        heading: "Factors that affect dissertation proofreading turnaround",
        paragraphs: [["A 12,000-word dissertation with clean formatting is different from a 45,000-word dissertation with many tables, appendices, citations, and unresolved comments. The stronger the draft and the clearer the guidelines, the easier it is to confirm a realistic schedule."]],
        table: {
          headers: ["Factor", "Why it affects time", "What to prepare"],
          rows: [
            ["Word count", "More words require more reading and checking time", "Confirm the final word count before requesting a quote"],
            ["Draft quality", "Heavy sentence-level issues slow the review", "Send the most stable version available"],
            ["Tables and figures", "Captions, labels, numbers, and callouts need separate checks", "Provide final tables, figures, and source notes"],
            ["References", "Citation-reference matching takes time", "State the required style and supply source details"],
            ["Formatting", "Margins, headings, pagination, and appendices can shift", "Attach university guidelines"],
          ],
        },
      },
      {
        id: "review-passes",
        heading: "A good proofread uses more than one pass",
        paragraphs: [["A careful dissertation proofread may involve separate passes for language, consistency, references, formatting, tables and figures, and the exported final file. Combining everything into one rushed reading increases the chance of missed errors."]],
      },
      {
        id: "tracked-changes",
        heading: "Leave time to review tracked changes",
        paragraphs: [["Proofreading is not finished when the file returns to you. You need time to review corrections, respond to comments, accept or reject changes, refresh fields, export the final PDF, and inspect the submission file. Microsoft explains that tracked changes must be accepted or rejected to remove markup from a Word document; build that review step into your deadline.", { text: "Microsoft's Track Changes guidance", href: "https://support.microsoft.com/en-us/word/training/track-changes-in-word", external: true }]],
      },
      {
        id: "plan",
        heading: "How to plan your dissertation proofreading deadline",
        paragraphs: [["Start with the final submission date and work backwards. Reserve time for supervisor questions, formatting fixes, final PDF checks, and technical upload issues. For the full sequence, use our ", { text: "step-by-step dissertation proofreading workflow", href: "/blog/how-to-proofread-a-dissertation-before-submission" }, "."]],
      },
    ],
    faq: [
      { question: "Can a dissertation be proofread in 24 hours?", answer: "Sometimes only a limited final check is realistic in 24 hours. The answer depends on length, draft quality, formatting complexity, and availability." },
      { question: "Should I wait until formatting is complete?", answer: "Major content should be stable before proofreading. Formatting checks usually happen near the end, followed by a final PDF inspection." },
      { question: "Do long dissertations need custom review?", answer: "Yes. Very long or complex dissertations should be scoped before payment so the schedule and deliverables are realistic." },
    ],
    internalLinks: [
      { href: "/dissertation-proofreading", label: "Dissertation proofreading", description: "Review the service scope for long graduate submissions." },
      { href: "/pricing", label: "Check pricing", description: "Estimate eligible projects by word count and turnaround." },
      { href: "/submit", label: "Submit your dissertation", description: "Upload the stable file and requirements securely." },
    ],
  },
  {
    title: "British vs American English in Academic Writing",
    slug: "british-vs-american-english-academic-writing",
    excerpt: "Compare British and American English in academic writing, including spelling, punctuation, terminology, quotation conventions, university rules, and consistency.",
    category: "Academic Editing",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "7 min read",
    metaTitle: "British vs American English in Academic Writing",
    metaDescription: "Compare British vs American English in academic writing for spelling, punctuation, terminology, quotations, university rules, and consistency.",
    heroImage: "/images/blog/research-philosophy-thesis-guide.webp",
    heroImageAlt: "Academic draft showing British and American English spelling choices marked for consistency",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "spelling", label: "Spelling" },
      { id: "punctuation", label: "Punctuation" },
      { id: "terminology", label: "Terminology" },
      { id: "rules", label: "University or journal rules" },
      { id: "consistency", label: "Consistency checklist" },
    ],
    body: [
      { id: "quick-answer", heading: "British vs American English: choose one and stay consistent", paragraphs: [["In academic writing, British and American English can both be correct. The problem is inconsistency. Follow your university, department, journal, or publisher rules first, then apply one variety consistently across spelling, punctuation, terminology, references, headings, tables, and figures."]] },
      { id: "spelling", heading: "Spelling differences to check", paragraphs: [["Common differences include endings such as -ise or -ize, -our or -or, and -re or -er. Some journals accept either variety if the manuscript is consistent, while others specify one. Search the whole document rather than checking only body paragraphs."]], table: { headers: ["Area", "British English example", "American English example"], rows: [["Spelling", "analyse, colour, centre", "analyze, color, center"], ["Quotation punctuation", "Often follows the required style guide", "Often follows the required style guide"], ["Date style", "Often day-month-year", "Often month-day-year"]] } },
      { id: "punctuation", heading: "Punctuation and quotation conventions", paragraphs: [["Quotation-mark placement, punctuation with citations, serial comma use, and date formatting can vary by style guide. Do not rely only on national variety; APA, MLA, Chicago, house style, or university rules may decide the convention."]] },
      { id: "terminology", heading: "Terminology and academic vocabulary", paragraphs: [["Vocabulary can differ by region. Terms such as programme/program, module/course, mark/grade, and dissertation/thesis may carry different meanings depending on country and institution. Use the terminology expected by your reader."]] },
      { id: "rules", heading: "University or journal rules come first", paragraphs: [["If your university or target journal specifies British or American English, follow that instruction even if your personal preference differs. If no rule is given, choose the variety most appropriate for the audience and apply it consistently."]] },
      { id: "consistency", heading: "British and American English consistency checklist", paragraphs: [["Before submission, search for spelling variants, date formats, punctuation patterns, headings, table text, figure captions, appendices, references, and file names. A professional ", { text: "academic proofreading service", href: "/academic-proofreading" }, " can help catch mixed usage across long documents."]], bullets: [["Search for common spelling pairs."], ["Check captions and table cells."], ["Review references and title capitalization according to the required style."], ["Confirm the English variety in journal or university instructions."]] },
    ],
    faq: [
      { question: "Is British English better for academic writing?", answer: "No. British and American English can both be acceptable. The required style depends on your university, journal, publisher, discipline, and audience." },
      { question: "Can I mix British and American spelling?", answer: "Avoid mixing spelling varieties unless a quoted source or official title requires it. Consistency makes the document easier to read and review." },
      { question: "Should references be changed to match my English variety?", answer: "Do not change the spelling of source titles unless the required style explicitly allows title-case or sentence-case adjustments. Preserve source details accurately." },
    ],
    internalLinks: [
      { href: "/academic-proofreading", label: "Academic proofreading", description: "Check language consistency before academic submission." },
      { href: "/translation-review", label: "Translation review", description: "Polish translated English for natural phrasing and terminology." },
      { href: "/blog/thesis-proofreading-checklist", label: "PhD thesis checklist", description: "Use a long-document final review checklist." },
    ],
  },
  {
    title: "Common APA 7 Reference List Errors Before Submission",
    slug: "apa-7-reference-list-mistakes",
    excerpt: "Review common APA 7 reference list mistakes before submission, including missing entries, author names, dates, titles, DOIs, URLs, and hanging indents.",
    category: "Formatting and References",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "8 min read",
    metaTitle: "APA 7 Reference List Mistakes Before Submission",
    metaDescription: "Check common APA 7 reference list mistakes before submission, including missing entries, author names, dates, titles, DOIs, URLs, and formatting.",
    heroImage: "/images/blog/thesis-tables-figures-references-checklist.webp",
    heroImageAlt: "Reference list and citation notes being checked before academic submission",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "missing-mismatched", label: "Missing or mismatched entries" },
      { id: "elements", label: "Reference elements" },
      { id: "doi-url", label: "DOIs and URLs" },
      { id: "formatting", label: "Formatting" },
      { id: "final-check", label: "Final check" },
    ],
    body: [
      { id: "quick-answer", heading: "APA 7 reference list mistakes to check first", paragraphs: [["The most important APA 7 reference-list errors are missing entries, uncited entries, incorrect author names, wrong dates, inconsistent titles, incomplete source details, broken DOIs or URLs, and formatting that does not follow the required institutional or publication rules."]] },
      { id: "missing-mismatched", heading: "1. Missing or mismatched citations and references", paragraphs: [["Every in-text citation should have a reference-list entry, and every reference-list entry should connect to a cited source unless your assignment has a different rule. Run the check in both directions before formatting the list."]] },
      { id: "elements", heading: "2. Incorrect reference elements", paragraphs: [["APA's official guidance organizes reference-list entries around author, date, title, and source elements. Use the ", { text: "APA reference examples", href: "https://apastyle.apa.org/style-grammar-guidelines/references/examples", external: true }, " and ", { text: "reference element guidance", href: "https://apastyle.apa.org/style-grammar-guidelines/references/elements-list-entry", external: true }, " to confirm the source type rather than guessing from memory."]], table: { headers: ["Element", "Common problem", "Safe check"], rows: [["Author", "Initials, group authors, or order are inconsistent", "Compare with the source record"], ["Date", "Year differs between citation and reference", "Check publication date"], ["Title", "Capitalization or italicization is inconsistent", "Follow APA and assignment rules"], ["Source", "Journal, publisher, DOI, or URL is incomplete", "Verify against the source page"]] } },
      { id: "doi-url", heading: "3. DOI and URL errors", paragraphs: [["Broken or incomplete DOI and URL details are common in final drafts. APA has separate ", { text: "DOI and URL guidance", href: "https://apastyle.apa.org/style-grammar-guidelines/references/dois-urls", external: true }, "; use it with your university instructions and verify that links resolve to the intended source."]] },
      { id: "formatting", heading: "4. Reference-list formatting problems", paragraphs: [["Check hanging indents, line spacing, alphabetization, punctuation, italics, capitalization, and entries that wrap awkwardly after copy-pasting from databases. Do not focus on spacing before confirming that the source details are correct."]] },
      { id: "final-check", heading: "Final APA 7 reference-list check", paragraphs: [["Before submission, compare references against citations, update any reference manager output, test important links, and ask the author to confirm uncertain sources. A proofreader can flag visible inconsistencies, but authors remain responsible for source accuracy. Our ", { text: "academic proofreading service", href: "/academic-proofreading" }, " can include reference presentation checks within the supplied document."]] },
    ],
    faq: [
      { question: "Can a proofreader fix APA 7 references?", answer: "A proofreader can check visible consistency, formatting, missing details, and citation-reference matching in the supplied document. Full source verification should be agreed separately." },
      { question: "Should I include sources I read but did not cite?", answer: "Follow your assignment or publication rules. In most APA reference lists, entries should correspond to cited works rather than a broad reading list." },
      { question: "Can AI generate missing APA references?", answer: "Do not rely on AI to invent missing source details. Verify each author, date, title, DOI, and URL against a reliable record." },
    ],
    internalLinks: [
      { href: "/academic-proofreading", label: "Academic proofreading", description: "Check reference presentation and academic language before submission." },
      { href: "/document-formatting", label: "Document formatting", description: "Prepare reference-heavy files for final submission." },
      { href: "/blog/thesis-tables-figures-references-checklist", label: "Reference checklist", description: "Use a broader thesis tables, figures, and references audit." },
    ],
  },
  {
    title: "CV and Resume Proofreading Checklist Before Applying",
    slug: "cv-proofreading-checklist",
    excerpt: "Use this CV proofreading checklist before applying to check contact details, dates, tense, achievement wording, layout, spelling, file naming, and PDF export.",
    category: "Careers and Applications",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "7 min read",
    metaTitle: "CV Proofreading Checklist Before Applying",
    metaDescription: "Use this CV proofreading checklist before applying to check contact details, dates, tense, achievements, layout, spelling, file naming, and PDF export.",
    heroImage: "/assets/og-image.jpg",
    heroImageAlt: "CV and resume document being reviewed for spelling, dates, layout, and final export",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "checklist", label: "Checklist" },
      { id: "tailoring", label: "Role-specific tailoring" },
      { id: "final-file", label: "Final file" },
    ],
    body: [
      { id: "quick-answer", heading: "CV proofreading checklist: what to check before applying", paragraphs: [["Before sending a CV or resume, check contact details, job dates, tense, spelling, achievement wording, layout consistency, file naming, PDF export, and role-specific tailoring. A clean application document helps the reader scan your experience without avoidable distractions."]] },
      { id: "checklist", heading: "CV and resume proofreading checklist", paragraphs: [["Use this checklist after the content is complete and before uploading the file to an application portal."]], table: { headers: ["Area", "What to check", "Done"], rows: [["Contact details", "Email, phone, location, links, and profile URLs", "□"], ["Dates", "Employment dates, education dates, and month/year consistency", "□"], ["Tense", "Past roles in past tense; current role consistent", "□"], ["Achievements", "Specific truthful outcomes without invented metrics", "□"], ["Spelling", "Names, tools, employers, certifications, and keywords", "□"], ["Layout", "Headings, spacing, bullets, alignment, and page breaks", "□"], ["File name", "Clear professional file name with your name and document type", "□"], ["PDF export", "Open the exported file and check links, spacing, and page count", "□"]] } },
      { id: "tailoring", heading: "Tailor the CV without inventing experience", paragraphs: [["Role-specific tailoring means emphasizing relevant truthful experience, skills, tools, and outcomes. It does not mean inventing achievements, employers, qualifications, certifications, dates, or references. Our ", { text: "CV and resume editing service", href: "/cv-resume-editing" }, " improves the material you provide while preserving accuracy."]] },
      { id: "final-file", heading: "Final file checks before applying", paragraphs: [["Export the document to the requested file type, open it on another device if possible, test links, confirm the filename, and check that no comments or draft notes remain. Keep a separate editable copy for future applications."]] },
    ],
    faq: [
      { question: "Should a CV be proofread as a PDF or Word file?", answer: "Check both when possible. Edit in the source file, then inspect the exported PDF because spacing, links, and page breaks can change." },
      { question: "Can an editor improve my CV achievements?", answer: "An editor can improve clarity and wording using the facts you provide. They should not invent achievements, metrics, employers, dates, or qualifications." },
      { question: "Is a resume proofreading checklist enough?", answer: "A checklist helps with final errors. If the document needs stronger structure, focus, or wording, CV editing may be more useful." },
    ],
    internalLinks: [
      { href: "/cv-resume-editing", label: "CV and resume editing", description: "Improve application documents without inventing experience." },
      { href: "/proofreading-services", label: "Proofreading services", description: "Get a final check for completed professional documents." },
      { href: "/submit", label: "Submit your CV", description: "Upload the application document securely for review." },
    ],
  },
  {
    title: "Business Proposal Proofreading Checklist Before Sending",
    slug: "business-proposal-proofreading-checklist",
    excerpt: "Use this business proposal proofreading checklist before sending a client-ready proposal, including names, figures, dates, scope, pricing, grammar, formatting, and final PDF checks.",
    category: "Business Writing",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "7 min read",
    metaTitle: "Business Proposal Proofreading Checklist",
    metaDescription: "Use this business proposal proofreading checklist to check client names, figures, dates, scope, deliverables, pricing, grammar, formatting, and final PDF.",
    heroImage: "/images/hero/editor_business_1777475328522.png",
    heroImageAlt: "Business proposal being proofread before client delivery",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "proposal-checklist", label: "Checklist" },
      { id: "version-control", label: "Version control" },
      { id: "final-pdf", label: "Final PDF" },
    ],
    body: [
      { id: "quick-answer", heading: "Business proposal proofreading before sending", paragraphs: [["A business proposal should be proofread after the offer, scope, deliverables, pricing, dates, and approvals are final. The last review should catch errors that weaken trust: wrong client names, inconsistent figures, unclear scope wording, grammar problems, formatting slips, and the wrong file version."]] },
      { id: "proposal-checklist", heading: "Business proposal proofreading checklist", paragraphs: [["Use this checklist before sending a client-facing proposal."]], table: { headers: ["Area", "What to check", "Done"], rows: [["Client name", "Company name, contact name, spelling, and pronouns", "□"], ["Figures", "Totals, percentages, quantities, dates, and units", "□"], ["Scope", "Services, exclusions, assumptions, and responsibilities", "□"], ["Deliverables", "Names, order, deadlines, and acceptance criteria", "□"], ["Pricing", "Currency, taxes, payment schedule, and totals", "□"], ["Grammar", "Typos, punctuation, repeated words, and sentence clarity", "□"], ["Formatting", "Headings, tables, bullets, branding, and page breaks", "□"], ["Final PDF", "Links, filename, metadata, attachments, and email subject", "□"]] } },
      { id: "version-control", heading: "Control the final proposal version", paragraphs: [["Many proposal errors happen because an old file is sent after pricing or scope changes. Keep one approved final version, remove duplicate drafts, and make sure every attachment matches the email or portal submission."]] },
      { id: "final-pdf", heading: "Check the final PDF and delivery package", paragraphs: [["Open the PDF you will actually send. Check page breaks, table widths, clickable links, image quality, signatures, appendices, file name, and whether the email includes every promised attachment. Our ", { text: "business proofreading service", href: "/business-proofreading" }, " can review client-ready documents before delivery."]] },
    ],
    faq: [
      { question: "When should I proofread a business proposal?", answer: "Proofread after the offer, scope, pricing, dates, and internal approvals are final. Earlier drafts may need editing rather than final proofreading." },
      { question: "Can proofreading improve proposal strategy?", answer: "Proofreading checks correctness and consistency. If the proposal needs stronger positioning, order, or messaging, use editing before proofreading." },
      { question: "Should proposal numbers be fact-checked?", answer: "The business remains responsible for approving figures, pricing, and claims. A proofreader can flag visible inconsistencies for confirmation." },
    ],
    internalLinks: [
      { href: "/business-proofreading", label: "Business proofreading", description: "Review client-facing proposals, reports, and business documents." },
      { href: "/editing-services", label: "Editing services", description: "Improve structure and message before final proofreading." },
      { href: "/submit", label: "Submit a proposal", description: "Upload a final business document securely." },
    ],
  },
  {
    title: "Manuscript Editing vs Copyediting vs Proofreading for Authors",
    slug: "manuscript-editing-vs-copyediting",
    excerpt: "Authors can compare manuscript editing, copyediting, and proofreading, including what each stage improves and when a book or research manuscript needs each review.",
    category: "Research and Manuscripts",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "8 min read",
    metaTitle: "Manuscript Editing vs Copyediting vs Proofreading",
    metaDescription: "Compare manuscript editing vs copyediting vs proofreading for authors, including scope, timing, book manuscripts, research papers, and final review.",
    heroImage: "/images/blog/editing-proofreading-manuscript-submission.webp",
    heroImageAlt: "Author manuscript pages marked for editing, copyediting, and proofreading stages",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "manuscript-editing", label: "Manuscript editing" },
      { id: "copyediting", label: "Copyediting" },
      { id: "proofreading", label: "Proofreading" },
      { id: "comparison", label: "Comparison" },
      { id: "choose", label: "How authors choose" },
    ],
    body: [
      { id: "quick-answer", heading: "Manuscript editing vs copyediting vs proofreading", paragraphs: [["For authors, manuscript editing improves the larger reading experience, copyediting improves sentence-level clarity and consistency, and proofreading checks the final approved version for surface errors. The right stage depends on whether the manuscript still needs development, language refinement, or final correction."]] },
      { id: "manuscript-editing", heading: "Manuscript editing improves the reader's experience", paragraphs: [["Manuscript editing can address chapter flow, pacing, organization, argument, voice, repetition, transitions, and reader confusion. For research manuscripts, it may focus on section logic, cautious claims, terminology, and journal fit."]] },
      { id: "copyediting", heading: "Copyediting improves language and consistency", paragraphs: [["Copyediting sits closer to the sentence. It can improve wording, grammar, style, terminology, capitalization, abbreviations, and consistency across chapters or sections without taking over the author's ideas."]] },
      { id: "proofreading", heading: "Proofreading is the final check", paragraphs: [["Proofreading happens after editing decisions are complete. It checks grammar, spelling, punctuation, typos, formatting slips, captions, page elements, and final presentation. For the broad distinction, see ", { text: "editing vs proofreading", href: "/blog/editing-vs-proofreading" }, "."]] },
      { id: "comparison", heading: "Author-focused comparison", paragraphs: [["Use this table to identify the stage your manuscript is actually in."]], table: { headers: ["Stage", "Best timing", "Main focus"], rows: [["Manuscript editing", "When chapters or sections still need strengthening", "Structure, flow, voice, argument, readability"], ["Copyediting", "When the manuscript is complete but language needs refinement", "Sentences, style, consistency, clarity"], ["Proofreading", "After edits are accepted and the file is close to final", "Typos, grammar, punctuation, formatting, final presentation"]] } },
      { id: "choose", heading: "How authors choose the right review", paragraphs: [["Choose ", { text: "manuscript editing services", href: "/manuscript-editing" }, " when readers may struggle with structure, flow, clarity, or consistency. Choose ", { text: "professional proofreading services", href: "/proofreading-services" }, " when the manuscript is final and only needs a last careful check."]], bullets: [["Early draft: manuscript editing."], ["Complete but uneven language: copyediting or line editing."], ["Final approved manuscript: proofreading."], ["Submission-ready file with complex presentation: proofreading plus formatting review."]] },
    ],
    faq: [
      { question: "Do authors need both editing and proofreading?", answer: "Many manuscripts benefit from both. Editing improves the manuscript, while proofreading checks the final approved version after edits are accepted." },
      { question: "Is copyediting the same as proofreading?", answer: "No. Copyediting improves language and consistency before final approval. Proofreading checks the finished file for remaining errors." },
      { question: "Can editing guarantee publication?", answer: "No. Editing can improve communication and presentation, but publication depends on many decisions outside the editor's control." },
    ],
    internalLinks: [
      { href: "/manuscript-editing", label: "Manuscript editing", description: "Review long-form manuscripts for clarity, structure, and consistency." },
      { href: "/proofreading-services", label: "Professional proofreading", description: "Get a final human check after editing is complete." },
      { href: "/blog/editing-and-proofreading-before-manuscript-submission", label: "Manuscript submission guide", description: "Prepare a manuscript before submission." },
    ],
  },
  {
    title: "How to Prepare a Document for Professional Editing",
    slug: "prepare-document-for-proofreading",
    excerpt: "Prepare a document for professional editing or proofreading by freezing the right version, providing guidelines, explaining the audience, cleaning tracked changes, and sharing deadlines.",
    category: "Editing services",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "8 min read",
    metaTitle: "Prepare a Document for Proofreading or Editing",
    metaDescription: "Learn how to prepare a document for proofreading or editing, including version control, guidelines, audience notes, deadlines, Track Changes, and source files.",
    heroImage: "/assets/premium_desk.png",
    heroImageAlt: "Professional editing desk with documents prepared for review",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "version", label: "Correct version" },
      { id: "guidelines", label: "Guidelines" },
      { id: "audience", label: "Audience and deadline" },
      { id: "tracked-changes", label: "Tracked changes" },
      { id: "submit", label: "Submit cleanly" },
    ],
    body: [
      { id: "quick-answer", heading: "How to prepare a document for professional editing", paragraphs: [["Before sending a document for editing or proofreading, freeze the correct version, provide the guidelines, identify the audience, explain the deadline, clean unresolved tracked changes where appropriate, supply the reference style, remove duplicate files, and include source text for translation review when available."]] },
      { id: "version", heading: "Freeze the correct version", paragraphs: [["Choose the version you want reviewed and stop making parallel edits. If multiple people are still changing the document, assign one person to combine changes before submission."]] },
      { id: "guidelines", heading: "Provide the rules the editor should follow", paragraphs: [["Attach university guidelines, journal instructions, publisher rules, company style guides, word limits, marking criteria, reference style, or client requirements. Specific rules are more useful than broad instructions such as 'make it better.'"]] },
      { id: "audience", heading: "Explain the audience, purpose, and deadline", paragraphs: [["Tell the editor who will read the document and what the document must do. A business proposal, PhD chapter, CV, translated report, and journal manuscript need different editorial judgment."]] },
      { id: "tracked-changes", heading: "Clean tracked changes and comments carefully", paragraphs: [["If the document has unresolved Track Changes, decide whether the editor should review them, ignore them, or work from a clean version. Microsoft explains how to accept or reject tracked changes in Word; use that process only when you are ready to finalize those edits.", { text: "Microsoft Track Changes support", href: "https://support.microsoft.com/en-us/word/accept-or-reject-tracked-changes-in-word", external: true }]] },
      { id: "submit", heading: "Submit the document with the right service notes", paragraphs: [["Use ", { text: "editing services", href: "/editing-services" }, " for clarity, tone, flow, and structure. Use ", { text: "proofreading services", href: "/proofreading-services" }, " for final correction. For translated English, include the source text when available and choose ", { text: "translation review", href: "/translation-review" }, ". Then ", { text: "upload the document securely", href: "/submit" }, "."]] },
    ],
    faq: [
      { question: "Should I send a Word file or PDF for proofreading?", answer: "An editable file is usually best for corrections. A PDF can also be useful for final layout checks when presentation matters." },
      { question: "Should I remove comments before sending a document?", answer: "Remove comments only if they are resolved. If a comment affects editorial decisions, leave it in or summarize the issue in your notes." },
      { question: "What if I do not know whether I need editing or proofreading?", answer: "Send the document condition, deadline, audience, and goals. The desk can help identify whether editing, proofreading, formatting, or translation review is more appropriate." },
    ],
    internalLinks: [
      { href: "/submit", label: "Submit your document", description: "Upload the correct file and notes securely." },
      { href: "/editing-services", label: "Editing services", description: "Choose deeper clarity, tone, and structure support." },
      { href: "/proofreading-services", label: "Proofreading services", description: "Choose a final correction pass for a stable document." },
    ],
  },
  {
    title: "How to Format a Thesis or Dissertation in Microsoft Word",
    slug: "format-thesis-in-microsoft-word",
    excerpt: "Learn how to format a thesis or dissertation in Microsoft Word with styles, heading levels, section breaks, page numbering, captions, table of contents, cross-references, and final PDF checks.",
    category: "Formatting and References",
    author,
    datePublished: published,
    dateUpdated: published,
    readingTime: "9 min read",
    metaTitle: "How to Format a Thesis in Microsoft Word",
    metaDescription: "Learn how to format a thesis in Microsoft Word with styles, headings, section breaks, page numbering, captions, contents lists, cross-references, and PDF checks.",
    heroImage: "/images/blog/thesis-tables-figures-references-checklist.webp",
    heroImageAlt: "Thesis document formatted in Microsoft Word with headings, captions, and table of contents checks",
    tableOfContents: [
      { id: "quick-answer", label: "Quick answer" },
      { id: "styles", label: "Styles and headings" },
      { id: "sections", label: "Section breaks and numbering" },
      { id: "captions", label: "Captions and cross-references" },
      { id: "contents", label: "Contents lists" },
      { id: "final-pdf", label: "Final PDF" },
    ],
    body: [
      { id: "quick-answer", heading: "How to format a thesis in Microsoft Word", paragraphs: [["Format a thesis or dissertation in Word by using paragraph styles for headings, planning section breaks before page numbering, creating captions for tables and figures, inserting cross-references, generating the table of contents from headings, updating fields, and checking the final exported PDF. Always follow your institution's formatting rules first."]] },
      { id: "styles", heading: "Use styles for heading levels", paragraphs: [["Word's table of contents is based on headings, according to ", { text: "Microsoft's table of contents guidance", href: "https://support.microsoft.com/en-US/Word/training/insert-a-table-of-contents", external: true }, ". Apply Heading 1, Heading 2, and Heading 3 consistently instead of manually enlarging text to look like a heading."]] },
      { id: "sections", heading: "Plan section breaks and page numbering", paragraphs: [["Theses often use different numbering for front matter and main chapters. Set section breaks deliberately before adjusting page numbers, headers, and footers. After any layout change, inspect the document page by page because section breaks can affect later chapters."]] },
      { id: "captions", heading: "Use captions and cross-references for tables and figures", paragraphs: [["Create captions before cross-referencing tables, figures, headings, or page numbers. Microsoft notes that a cross-reference links to an item already present in the document and can be inserted as a hyperlink.", { text: "Microsoft cross-reference guidance", href: "https://support.microsoft.com/en-us/word/create-a-cross-reference", external: true }]] },
      { id: "contents", heading: "Update the table of contents and lists", paragraphs: [["After headings, captions, and pagination are stable, update the table of contents, list of tables, and list of figures. Missing entries often indicate that the heading or caption was not created with the correct Word feature."]] },
      { id: "final-pdf", heading: "Check the final PDF before submission", paragraphs: [["Export the exact file required by your university and inspect every page. Check page breaks, fonts, images, equations, table widths, bookmarks, hyperlinks, file size, and filename. Our ", { text: "document formatting service", href: "/document-formatting" }, " can help prepare complex thesis and dissertation files."]] },
    ],
    faq: [
      { question: "Should I use manual headings in a thesis?", answer: "Use Word heading styles when possible. Manual formatting can look correct but fail to appear properly in generated contents lists." },
      { question: "When should I update the table of contents?", answer: "Update it after headings, captions, and pagination are stable, then inspect the generated entries and page numbers manually." },
      { question: "Can formatting replace proofreading?", answer: "No. Formatting addresses presentation. Proofreading checks language and consistency. Many final theses need both." },
    ],
    internalLinks: [
      { href: "/document-formatting", label: "Document formatting", description: "Prepare thesis and dissertation files for submission." },
      { href: "/blog/thesis-tables-figures-references-checklist", label: "Tables and references checklist", description: "Audit captions, cross-references, citations, and final files." },
      { href: "/submit", label: "Submit your thesis", description: "Upload the file and formatting requirements securely." },
    ],
  },
];
